FROM docker.io/httpd:latest
#COPY ./public-html/index.html /var/www/html/index.html
COPY ./public-html/index.html /usr/local/apache2/htdocs/
#echo 'Bonjour de la Terre 1 !' > /var/www/html/index.html
EXPOSE 8090
#httpd -D FOREGROUND
